### ISSUE TITLE
Potentially uninitialized local variable used `partition`

### ISSUE THREAD

**Issue by Gocnak** [iOrange/bcdec#10]
Hello! Your library is excellent and I wanted to report this warning we got from integrating bcdec into our engine.

`Warning	C4701	potentially uninitialized local variable 'partition'`
https://github.com/iOrange/bcdec/blob/main/bcdec.h#L870

It seems like there's a very rare case that could happen where partition is uninitialized. I noticed [the if-else block above on L829](https://github.com/iOrange/bcdec/blob/main/bcdec.h#L829) sets it to 0 but only in the if, not the else. I'm not too knowledgeable on BC formats so I wouldn't know what the proper value to set it here would be, hence me reporting this warning we get in an issue rather than submitting a PR. 😅

**Comment by iOrange** [comment]
Hi!

All modes < 10 get their partition from the bitstream, and every mode >= 10 is using partition 0.
My guess is that your compiler get's confused. Could you please specify your compiler so that I could try to repro this warning ?

**Comment by iOrange** [comment]
Actually, to play it safe I can just init partition to 0 at start and then read it from bitstream for modes that require it. This should make any compiler happy :)

**Comment by iOrange** [comment]
Should be resolved by 026acf98ea271045cb10713daa96ba98528badb7.
Please let me know if that fixed your warning and I'll close this issue.
Thanks!

**Comment by Gocnak** [comment]
Perfect, this fixes it nicely! Thank you so much.

We use the latest MSVC (C++23) to compile this library as part of our engine for Windows, and clang v14 for Linux, for future reference.
