### ISSUE TITLE
How do i compile this???

### ISSUE THREAD

**Issue by guranu** [iOrange/bcdec#11]
How do i compile this thing?
Also does this support raw textures?

**Comment by iOrange** [comment]
Hi, not sure I understand the question.
This is basically a "one header library", so if you want to use it - you just copy "bcdec.h" to you project folder and include it and use it's functions.

The accompanying it example application shows simple use case, and you can compile it using the provided CMakeLists.txt  CMake script.

**Comment by guranu** [comment]
> Hi, not sure I understand the question. This is basically a "one header library", so if you want to use it - you just copy "bcdec.h" to you project folder and include it and use it's functions.
> 
> The accompanying it example application shows simple use case, and you can compile it using the provided CMakeLists.txt CMake script.

I'm on linux so the only way for me to use this is to compile however when trying compile it i get this error
![Screenshot_20230209-104400_1](https://user-images.githubusercontent.com/103632948/217748324-0a04d85a-dca7-4148-aea0-d98c20834be8.jpg)

**Comment by iOrange** [comment]
Interesting, I'll dust off my Linux machine and will give it a try

**Comment by scurest** [comment]
@guranu 
I think it just needs `-lm`, see [eg](https://stackoverflow.com/questions/34625627/how-to-link-to-the-c-math-library-with-cmake). Can you try adding `target_link_libraries (bcdec m)` at the bottom of CMakeLists.txt and see if that fixes it?

**Comment by guranu** [comment]
> 

Adding `target_link_libraries (bcdec m)` in the CMakeLists.txt worked.
