### ISSUE TITLE
Remove implementation from include guard

### ISSUE THREAD

**Issue by Puxtril** [iOrange/bcdec#13]
I'm having issues adding this to my C++ project. Here's the issues I'm running into:

I have files `TextureConverter.h` and `TextureConverter.cpp`. Naturally, `TextureConverter.cpp` includes `TextureConverter.h`. I'm including `bcdec.h` in my header and defining `BCDEC_IMPLEMENTATION`.  Problem is, this defines bcdec's implementation wherever `TextureConverter.h` is included, so this leads to _mutiple definition_ compiler errors. So my workaround is to include `bcdec.h` in both `TextureConverter.h` and `TextureConverter.cpp`, but only define `BCDEC_IMPLEMENTATION` in the source file. The catch is, `bcdec.h` wraps its implementation _inside_ the include guard, so including `TextureConverter.h` in my source prevents me from including bcdec again. To me, it seems the include guard should only wrap the definition, not the implementation.

That was a long justification for my [one-line change](https://github.com/Puxtril/bcdec/commit/c041658bd48f1dfb0a3395647ffb63b987b7d7bd). I can open a pull request if you think this will be beneficial.

**Comment by iOrange** [comment]
Yeah you're right, please make a pull request and I'll merge it in.
