### ISSUE TITLE
Source code license terms

### ISSUE THREAD

**Issue by NPCompress** [iOrange/bcdec#2]
I am the team lead for Compressonator Tool, and would like to consider adding your single header decoder code into the repo. In order to do this can your license terms be updated to the same as Compressonator source code which is MIT licensed.?

**Comment by iOrange** [comment]
@NPCompress I've updated the license - now the code is licensed under two licenses - MIT and The Unlicense, please choose whichever you prefer.

**Comment by iOrange** [comment]
Closing it since I believe having double license is sufficient for most projects.
