### ISSUE TITLE
Version define

### ISSUE THREAD

**Issue by bluescan** [iOrange/bcdec#9]
Hi iOrange. I'm thinking of using bcdec over at https://github.com/bluescan/tacentview. Would it be possible to put the version number at the top of the header as a define after the include guards... maybe same for etcdec too?

**Comment by iOrange** [comment]
In what form would you prefer it to be ?
As
`#define BCDEC_VERSION_MAJOR 0`
`#define BCDEC_VERSION_MINOR 9`
`#define BCDEC_VERSION_REVISION 5`
or
`#define BCDEC_VERSION "0.95"`
?

**Comment by bluescan** [comment]
Slightly prefer the integer defines but can work with either. If you do go with the 3 int defines (major minor rev), what you have above would be version 0.9.5 whereas your string only has a major of 0 and a minor of 95 ("0.95").

So overall pref is:
```
#define BCDEC_VERSION_MAJOR 0
#define BCDEC_VERSION_MINOR 95
#define BCDEC_VERSION_REVISION 0
```

(Your decoder is working great btw. I've got BC 1 to 7 all decoding in the base library dds-loader without issue. TY!)

**Comment by iOrange** [comment]
3b71535 added defines for major/minor version. Sorry it took so long.

**Comment by bluescan** [comment]
Thanks for the update! Just grabbed the new version with the new magic decode numbers.
